### ISSUE TITLE
file / message transfere problem when include

### ISSUE THREAD

**Issue by hjochman** [dillpixel/fitbit-google-analytics#4]
Hi, I included the API into my app https://github.com/hjochman/fitbit-schedule
The app also uses the file / messaging api to transfer data and files between the watch and the companion app. This is not working stable when the API is included.

The watch app is not able anymore to receive any messages or file from the companion.

**Comment by daveyjones** [comment]
@hjochman thanks for the bug report. We can clone your repo to see if we can reproduce. @MathewReiss do you think the new file API has issues with multiple listeners?

**Comment by hjochman** [comment]
@MathewReiss I understand your idea, but can't find anything in the Readme.MD about the configuration possibility you described

**Comment by hjochman** [comment]
I checked your code and what is relay strange is that you only user file transfer and messages from the app to the companion.
My app uses file transfer and messages from companion to app and only messages from app to companion.
But also the files I send from the companion to the app are not received as soon as I include your code.

**Comment by pbr0ck3r** [comment]
I can confirm that I am also receiving this same error.

**Comment by pbr0ck3r** [comment]
@daveyjones The video is not mine, but I found it as it was promoted by Jon Barlow (one of the head Fitbit Devs) on twitter. I tried updating the devDependencies but am still getting the error.

**Comment by daveyjones** [comment]
@pbr0ck3r Ah—got it...thought you made the video :-)

Did you run `npm install` after making changes to `package.json`? The language of that error sounds like the new `fileTransfer` method introduced in SDK 3.0 doesn't exist. Just to be 100% certain, what do you get when you add this to your app code?

```
console.log("firmware version: " + device.firmwareVersion);
```

**Comment by hjochman** [comment]
> @daveyjones The video is not mine, but I found it as it was promoted by [Jon Barlow](https://twitter.com/orviwan) (one of the head Fitbit Devs) on twitter. Pretty sure he wouldn't mind you link the video (but would probably be nice to ask!) I tried updating the devDependencies but am still getting the error. Definitely up for helping debug and fix this issue for sure!

Hi, to update to SDK3 I needed to remove the npm_module folder and make an npm install after changing the package.jason. After that the error you had was gone fore me.

**Comment by pbr0ck3r** [comment]
@daveyjones Yeah i ran `npm install`. Found that like @hjochman said wiping the node_modules and start fresh seemed to work!

**Comment by pbr0ck3r** [comment]
@daveyjones Like you said earlier.. would be nice to figure out some backwards compatibility with SDK 1/2. As a lot of people haven't update to SDK version 3 yet.

**Comment by daveyjones** [comment]
@pbr0ck3r Thanks for the update! Glad it's working now. I updated the docs to make it clear that the current version only works with SDK 3.0 and anyone targeting previous SDK versions should keep using `npm install fitbit-google-analytics@1.1.0` for a while until most people have upgraded to 3.0.

**Comment by pbr0ck3r** [comment]
@daveyjones See the updated docs! Nice work! I tried using version `1.1.0` of the app but received the same errors as before. Wiped nod_modules and clean install. 

```
"devDependencies": {
  "@fitbit/sdk": "~1.0.0",
  "@fitbit/sdk-cli": "^1.0.0"
}
```

**Comment by daveyjones** [comment]
@hjochman Can you include steps to reproduce the error related to Google Analytics? I cloned your repo but I seem to be getting errors that are not related:
```
[7:31:23 AM] Companion: TypeError: Cannot read property 'name' of null
  i at companion/iCalendar.js:35,44
  loadEvents at companion/iCalendar.js:19,9
  a at sim-file:/bootstrap:63,35
  t.e.dispatchEvent at sim-file:/bootstrap:76,1
  t.dispatchEvent at sim-file:/bootstrap:622,87
  ? at undefined:1,33
  EventEmitter.electron.ipcRenderer.on (/Applications/Fitbit OS at Simulator.app/Contents/Resources/electron.asar/renderer/web-frame-init.js:36,30
  EventEmitter.emit at events.js:182,13
```
What steps do I need to take to get to the Google Analytics error?

**Comment by daveyjones** [comment]
Also, if you're willing to let me take a look at the code I'd be happy to do so—you can email me at david@dillpixel.com.

**Comment by daveyjones** [comment]
@pbr0ck3r Also, if you're willing to let me take a look at the code I'd be happy to do so—you can email me at david@dillpixel.com.

**Comment by hjochman** [comment]
@daveyjones  
You need to open the settings and setup at least one calendar to get the app normal working. 
Set a Name for Calendar 1 and a ICAL url (e.g https://www.officeholidays.com/ics/ics_country_code.php?iso=US for the us holidays)
When you restart the app the error should be gone and you should, after a short while, see the up cumming holiday on the watch.

If you comment in the google analytics code you will see that events in google analytics, but the request from the watch to update the calendar or the nintical load will not work. You will see the download in the companion app and the debug message that it send the file to the watch but it is never received.
The same for any changes in the settings. The are send from the companion to the watch, but they will never be reseived as soon as the google analytic code is running.

**Comment by daveyjones** [comment]
@hjochman Is the GitHub repo up-to-date with your localhost repo? After cloning the repo, adding the calendar URL for U.S. holidays, and restarting the app in the simulator, I'm still getting errors unrelated to Google Analytics.

**Comment by pbr0ck3r** [comment]
@daveyjones Chris the creator of the video got back to me and said he would love if we linked in the readme/docs.

**Comment by hjochman** [comment]
@daveyjones I reworked the error handling and retested it and now it is working without problems. Very strange. I only added one more check for null and some try catch statements. No change to the general handling of the file / message transfer or any other objects.  

I will keep an I on it if the problems reappear. Thank you for the code and for the quick response.

**Comment by daveyjones** [comment]
@hjochman That's great to hear! I'm glad it's working for you. I think the issue @pbr0ck3r was having is also resolved and we got the documentation updated to explain the SDK dependency, so I'm going to go ahead and close this issue.
