### ISSUE TITLE
Clock Face Error after adding this package to an existing watch face

### ISSUE THREAD

**Issue by BaronVonPerko** [dillpixel/fitbit-google-analytics#5]
Just recently updated the SDK and Fitbit-Google-Analytics package this weekend, so this issue may be resolved with the newest version.

SDK v3.0
Fitbit-Google-Analytics v1.2

I've been receiving emails from users that they are getting an error using my watch face "Clock Face Error".

I haven't been able to replicate it (my wife and I each have a Versa and haven't had this issue).  I'm thinking it may have to do with users in areas where the network isn't very reliable.

I wanted to see if you had experienced this error at all using this package?  We have had our watch face in the store for several months and did not receive these messages until just recently when we added this package to see the analytics.

If I'm ever able to reproduce it, I will add the stack trace to this issue.  Thanks!

**Comment by daveyjones** [comment]
Hey Chris—thanks for taking the time to submit this issue! I haven't heard of anyone else having this issue but this module is still pretty new so there are bound to be some edge cases we haven't thought of. I'll keep this issue open and keep an eye out for other reports. Hopefully we can find out how to reproduce and resolve.

**Comment by BaronVonPerko** [comment]
@daveyjones I just re-read the README and noticed that the "run_background" permission should be added.  I currently don't have that in my app.  I'll add that this evening and publish a new build and see if any more users email me regarding this issue.

**Comment by daveyjones** [comment]
@BaronVonPerko sounds good. Not having that permission set would prevent file transfers from occurring unless the Fitbit app is running, so that could create some problems. I'm not sure it would actually throw a critical error though. Maybe you could email those specific users to see if upgrading solves their issue.

**Comment by BaronVonPerko** [comment]
Had one user get back to me and said they are not having any more issues.  I've also not received a single email regarding this issue after I released this latest version.

My guess is this was related to still using an old version of the FitBit SDK, and not this package.  I'll close the ticket.  Thanks for your help! :+1:

**Comment by daveyjones** [comment]
Awesome—thanks for following up!
