### ISSUE TITLE
Clean up files on companion after hit is recorded

### ISSUE THREAD

**Issue by daveyjones** [dillpixel/fitbit-google-analytics#6]
Currently, files are not being deleted on the companion, so they will continue to accumulate indefinitely. A callback should be added to the `send` function that is called after the request to Google Analytics is made. The `process_files` function should then use this callback to delete the file.

Pull requests are welcome!

**Comment by tejas-patel** [comment]
I don't see them being cleaned up on device as well. Maybe clean up there as well?

**Comment by daveyjones** [comment]
@tejas-patel Thanks for your interest in the project! Files are never created on the device. Rather, data is passed directly into the `enqueue` function (as opposed to `enqueueFile`). I'm assuming that the File Transfer API cleans up after itself when using the `enqueue` function, but you bring up a good point and it would be a good idea to confirm that.

**Comment by daveyjones** [comment]
I've learned that files are only stored on the companion until `inbox.pop()` is called, at which point they are removed automatically. So this issue is...not an issue.

Since files are no longer available after `inbox.pop()`, we may want to consider adding some logic that prevents files from being popped if the phone does not have an active internet connection (and therefore can't send the hits to Google Analytics), but that's a separate issue so I'm closing this one for now.
