### ISSUE TITLE
Consider minifying your code 

### ISSUE THREAD

**Issue by badescuga** [dillpixel/fitbit-google-analytics#8]
From what I see in the package, the package might benefit from some minifying, especially on the app side.

**Comment by daveyjones** [comment]
@badescuga Thanks for your interest in the project! My understanding is that all code is minified by the build script, so I don't think there's any benefit to minification. I could be wrong on that, so I'll leave this open—if anyone knows more, please feel free to comment.

**Comment by badescuga** [comment]
You are correct. Minification was introduced in 2.x when the CLI came out, but it was done backwards to SDK 1.x as well. Sorry about the confusion.

You can close this.

**Comment by daveyjones** [comment]
Thanks for checking!
